document.documentElement.classList.add("js-ready");

// Remote Work Reality Check
// Reads real ACS work-from-home shares from window.WFH_DATA (generated by
// code/fetch_wfh_data.py -> website/data/wfh.js) and pairs each share with a
// literature-based interpretation. See knowledge base/reading-list.md.
(function () {
  "use strict";

  var calculator = document.getElementById("calculator");
  if (!calculator) {
    return;
  }

  // Mirrors the committed ACS 2023 numbers (remote-capable occupations only) so
  // the page still works if the data file fails to load. Replaced by
  // window.WFH_DATA when present.
  var FALLBACK = {
    year: 2023,
    cells: {
      "women|kids|ba": { share: 24.6, nUnweighted: 74908 },
      "women|kids|noba": { share: 16.7, nUnweighted: 51579 },
      "women|nokids|ba": { share: 24.5, nUnweighted: 160392 },
      "women|nokids|noba": { share: 17.0, nUnweighted: 128943 },
      "men|kids|ba": { share: 25.4, nUnweighted: 68241 },
      "men|kids|noba": { share: 14.8, nUnweighted: 35604 },
      "men|nokids|ba": { share: 25.5, nUnweighted: 150785 },
      "men|nokids|noba": { share: 15.7, nUnweighted: 92221 }
    }
  };

  var data = window.WFH_DATA && window.WFH_DATA.cells ? window.WFH_DATA : FALLBACK;
  var usingFallback = data === FALLBACK;

  var state = {
    sex: "women",
    kids: "kids",
    edu: "ba"
  };

  function key(s) {
    return s.sex + "|" + s.kids + "|" + s.edu;
  }

  function cell(s) {
    return data.cells[key(s)] || { share: 0, nUnweighted: 0 };
  }

  function oppositeSex(sex) {
    return sex === "women" ? "men" : "women";
  }

  function formatGap(value) {
    var sign = value > 0 ? "+" : value < 0 ? "\u2212" : "\u00b1";
    return sign + Math.abs(value).toFixed(1) + " pts";
  }

  function absGap(value) {
    return Math.abs(value).toFixed(1);
  }

  function numberWithCommas(n) {
    return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  }

  function sexLabel(sex) {
    return sex === "women" ? "women" : "men";
  }

  function childLabel(kids) {
    return kids === "kids" ? "with young children" : "without young children";
  }

  function eduLabel(edu) {
    return edu === "ba" ? "with bachelor's or higher" : "with less than bachelor's";
  }

  function getShare(sex, kids, edu) {
    return cell({ sex: sex, kids: kids, edu: edu }).share;
  }

  function buildVerdict(s, share, gap) {
    var isMother = s.kids === "kids";
    var subject;
    if (s.sex === "women") {
      subject = isMother ? "mothers of young children" : "women without young children";
    } else {
      subject = isMother ? "fathers of young children" : "men without young children";
    }
    subject = (s.edu === "ba" ? "college-educated " : "") + subject;

    var prevalence;
    if (share >= 18) {
      prevalence = "Working from home is common for " + subject + ".";
    } else if (share >= 12) {
      prevalence = "Working from home is only moderately common for " + subject + ".";
    } else {
      prevalence = "Working from home is rare for " + subject + ".";
    }

    var meaning;
    if (share >= 18) {
      meaning = " Where remote work is widely used, the research warns the cost shifts from dropping out to slower advancement: it can protect retention but cut promotion odds (Bloom et al. 2015; Emanuel & Harrington 2023/24).";
    } else {
      meaning = " Even though these jobs can be done remotely, relatively few here actually work from home, so the flexibility that might keep mothers attached to work is going partly unused (Collins et al. 2021).";
    }

    var gendered = "";
    if (s.sex === "women" && gap > 1) {
      gendered = " Notably, women here are " + gap.toFixed(1) + " points more likely to work from home than comparable men, hinting that remote work is absorbing caregiving load.";
    } else if (s.sex === "women" && gap < -1) {
      gendered = " Women here are " + Math.abs(gap).toFixed(1) + " points less likely to work from home than comparable men.";
    }

    return prevalence + meaning + gendered;
  }

  function render() {
    var c = cell(state);
    var share = c.share;

    var oppState = { sex: oppositeSex(state.sex), kids: state.kids, edu: state.edu };
    var gap = share - cell(oppState).share;
    var childState = { sex: state.sex, kids: state.kids === "kids" ? "nokids" : "kids", edu: state.edu };
    var childGap = share - cell(childState).share;
    var eduState = { sex: state.sex, kids: state.kids, edu: state.edu === "ba" ? "noba" : "ba" };
    var eduGap = share - cell(eduState).share;
    var genderGap = gap;

    var year = (window.WFH_DATA && window.WFH_DATA.year) || FALLBACK.year;

    setText("share", share.toFixed(1));
    setAll("year", year);

    var bar = calculator.querySelector('[data-out="bar"]');
    if (bar) {
      bar.style.width = Math.max(0, Math.min(100, share)) + "%";
      if (bar.parentNode && bar.parentNode.setAttribute) {
        bar.parentNode.setAttribute("aria-label", share.toFixed(1) + " percent worked from home");
      }
    }

    setText("gapLabel", "Gap vs " + oppositeSex(state.sex) + " (same group)");
    setText("gap", formatGap(gap));
    setText("genderCompareLabel", "Comparable " + sexLabel(oppState.sex));
    setText("genderCompare", formatGap(genderGap));
    setText("childCompareLabel", sexLabel(state.sex) + " " + childLabel(childState.kids));
    setText("childCompare", formatGap(childGap));
    setText("eduCompareLabel", sexLabel(state.sex) + " " + childLabel(state.kids) + " " + eduLabel(eduState.edu));
    setText("eduCompare", formatGap(eduGap));
    setText("comparisonInsight", buildComparisonInsight(state, genderGap, childGap, eduGap));
    setText("verdict", buildVerdict(state, share, gap));

    var sample = "Based on " + numberWithCommas(c.nUnweighted) + " surveyed workers, ACS " + year + ".";
    if (usingFallback) {
      sample += " (Showing built-in sample data; live file not loaded.)";
    }
    setText("sample", sample);
  }

  function buildComparisonInsight(s, genderGap, childGap, eduGap) {
    var prefix = "Among workers in remote-capable jobs, ";
    var largest = Math.max(Math.abs(genderGap), Math.abs(childGap), Math.abs(eduGap));
    if (largest === Math.abs(eduGap)) {
      if (s.edu === "ba") {
        return prefix + "the biggest gap here is still education: college-educated workers in this family situation are " + absGap(eduGap) + " points more likely to work from home than otherwise similar workers without a bachelor's degree.";
      }
      return prefix + "the biggest gap here is still education: workers without a bachelor's degree in this family situation are " + absGap(eduGap) + " points less likely to work from home than otherwise similar college-educated workers.";
    }
    if (largest === Math.abs(childGap)) {
      if (s.kids === "kids") {
        return prefix + "the child comparison stands out: having a young child is associated with a " + formatGap(childGap) + " difference in working from home for this sex and education group.";
      }
      return prefix + "the child comparison stands out: not having a young child is associated with a " + formatGap(childGap) + " difference in working from home for this sex and education group.";
    }
    return prefix + "the gender comparison stands out: this group differs from comparable " + sexLabel(oppositeSex(s.sex)) + " by " + formatGap(genderGap) + ", showing where remote-work uptake is gendered.";
  }

  function setText(name, value) {
    var el = calculator.querySelector('[data-out="' + name + '"]');
    if (el) {
      el.textContent = value;
    }
  }

  function setAll(name, value) {
    var els = document.querySelectorAll('[data-out="' + name + '"]');
    for (var i = 0; i < els.length; i++) {
      els[i].textContent = value;
    }
  }

  function selectValue(group, value) {
    var buttons = group.querySelectorAll("button");
    for (var i = 0; i < buttons.length; i++) {
      var isMatch = buttons[i].getAttribute("data-value") === value;
      buttons[i].setAttribute("aria-checked", isMatch ? "true" : "false");
      buttons[i].tabIndex = isMatch ? 0 : -1;
    }
  }

  function initGroup(group) {
    var inputName = group.getAttribute("data-input");
    var buttons = group.querySelectorAll("button");

    selectValue(group, state[inputName]);

    function choose(value) {
      state[inputName] = value;
      selectValue(group, value);
      render();
    }

    for (var i = 0; i < buttons.length; i++) {
      (function (button) {
        button.addEventListener("click", function () {
          choose(button.getAttribute("data-value"));
        });
      })(buttons[i]);
    }

    group.addEventListener("keydown", function (event) {
      var k = event.key;
      if (k !== "ArrowLeft" && k !== "ArrowRight" && k !== "ArrowUp" && k !== "ArrowDown") {
        return;
      }
      event.preventDefault();
      var list = Array.prototype.slice.call(buttons);
      var currentIndex = list.indexOf(document.activeElement);
      if (currentIndex === -1) {
        currentIndex = 0;
      }
      var delta = k === "ArrowLeft" || k === "ArrowUp" ? -1 : 1;
      var nextIndex = (currentIndex + delta + list.length) % list.length;
      var next = list[nextIndex];
      next.focus();
      choose(next.getAttribute("data-value"));
    });
  }

  var groups = calculator.querySelectorAll(".segmented");
  for (var g = 0; g < groups.length; g++) {
    initGroup(groups[g]);
  }

  render();
})();
